### ISSUE TITLE
Feature request - orderBy

### ISSUE THREAD

**Issue by adamtay** [morintd/prismock#502]
Hey there 👋

First off, thanks for providing this library. Really makes unit testing with Prisma a breeze.

When you get a chance, I'd love to request for the `orderBy` functionality.

Thanks!

**Comment by morintd** [comment]
Hello @adamtay , thanks a lot! I'm having a look, I hope to get it working in a few days!

**Comment by morintd** [comment]
Hello,

Good news, a new version has been published (1.15.0) with a first version of orderBy. 

I noted it as a partial implementation: different databases have different behaviours when it comes to ordering elements with the same values. Otherwise, the order is working as expected.

I'll close this issue for now. Feel free to let me know if you're experiencing issues with orderBy.

**Comment by samepant** [comment]
amazing! thanks for the update

**Comment by adamtay** [comment]
Thanks @morintd!
