### ISSUE TITLE
Nested Upsert

### ISSUE THREAD

**Issue by samepant** [morintd/prismock#521]
i'm loving Prismock and enjoying testing with it. Would love to get Nested Upserts supported!

thanks for supporting this package 🙏

**Comment by morintd** [comment]
Hello, thanks again 🙏 I'll try to add the support for nested upserts quickly!

**Comment by morintd** [comment]
I added a first version with support for nested upset, but it seems like [tests don't pass](https://github.com/morintd/prismock/pull/523), because of Prisma?

I'm saying it's because of Prisma because, when doing an upsert with a value that doesn't exist, Prisma create the element with the content of the `update` object inside the upsert (instead of `create`).

I wonder if that's a bug with Prisma, any help appreciated.

**Comment by morintd** [comment]
Hello @samepant , the support has now been added (in v1.19.0)!

**Comment by samepant** [comment]
just used this, thanks again!
