### ISSUE TITLE
Why is setData deprecated?

### ISSUE THREAD

**Issue by CrystallineCat** [morintd/prismock#898]
I currently rely on `setData()` in my E2E testing a NestJS backend. At the moment, objects are seeded in the beginning, then I take a snapshot of the DB with `getData()`, and before each test, I use `setData()` to restore that snapshot. I don't know how to do that without.

Is there a better way to do this?

**Comment by morintd** [comment]
Hello @CrystallineCat , `setData` is deprecated for two reasons:

- It forces us to re-generate the state of increments that are used with `autoincrement()` from Prisma (and more in the future).
- The same effect can be used by calling the `create`/`createMany` on the necessary models.

That would be my advice: instead of relying on `setData`, it would be better to create your data with `createMany`. If you have data generated by your database (such as `cuid()`), it might become a problem as some of your data will change.

I don't have a perfect solution there, either try to insert those data yourself or adapt your tests to take that into account.

**Comment by CrystallineCat** [comment]
Thank you for your answer, but I don't really understand the alternative. I'm very new to Prisma. At the moment, what I'm using is this:
```typescript
export const beforeEachResetData = (db: any) => {
  let data = null;

  beforeAll(() => {
    data = JSON.parse(JSON.stringify(db.getData()));
  });

  beforeEach(() => {
    db.setData(JSON.parse(JSON.stringify(data)));
  });
};
```

Can I replace this using the models without needing to know the details of the DB structure? If so, why not change `setData` to do that?

IDs are not managed by Prisma or the DBMS, so that is no concern for me.
