### ISSUE TITLE
Delete on prisma models throws an error

### ISSUE THREAD

**Issue by mxrcochxvez** [morintd/prismock#935]
For privacy reasons I am going to make this code as ambiguous as possible. However the concept very closely follows what I am trying to achieve.

posts.repo.ts
```typescript
export const postsRepo = { deletePosts };

function deletePosts(postId: string) {
    return prisma.posts.delete({ where: { id: postId } });
}
```

mock-prisma.ts (setupTests method)
```typescript
jest.mock('@prisma/client', () => {
	return {
		...jest.requireActual('@prisma/client'),
		PrismaClient: jest.requireActual('prismock').PrismockClient,
	};
});
```

posts.spec.ts
```typescript
test('it should delete a post', async () => {
    try {
        const result = await postsRepo.deletePosts('1');

        expect(results).toBeTruthy();
    } catch(error) {
        console.log(error);
    }
})
```

I am getting the following error

<img width="1399" alt="image" src="https://github.com/morintd/prismock/assets/43889446/c6cfa569-efb4-4494-af16-2afee6350d93">

**Comment by morintd** [comment]
Hello @mxrcochxvez , thanks a lot. Unfortunately, I don't have enough information to find where this issue is coming from. This might be related to your specific use case, would you be able to create a minimum reproductible example on a public repository? Maybe you have more information on the error too?
